# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lenovo/b8000/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lenovo/b8000/proprietary/bin/pvrsrvctl:system/bin/pvrsrvctl \
    vendor/lenovo/b8000/proprietary/bin/rc.fac:system/bin/rc.fac \
    vendor/lenovo/b8000/proprietary/lib/libwvdrm_L3.so:system/lib/libwvdrm_L3.so \
    vendor/lenovo/b8000/proprietary/lib/egl:system/lib/egl \
    vendor/lenovo/b8000/proprietary/lib/egl/libEGL_mtk.so:system/lib/egl/libEGL_mtk.so \
    vendor/lenovo/b8000/proprietary/lib/egl/libGLESv2_mtk.so:system/lib/egl/libGLESv2_mtk.so \
    vendor/lenovo/b8000/proprietary/lib/egl/libGLESv1_CM_mtk.so:system/lib/egl/libGLESv1_CM_mtk.so \
    vendor/lenovo/b8000/proprietary/lib/hw:system/lib/hw \
    vendor/lenovo/b8000/proprietary/lib/hw/gralloc.mt8389.so:system/lib/hw/gralloc.mt8389.so \
    vendor/lenovo/b8000/proprietary/lib/libIMGegl.so:system/lib/libIMGegl.so \
    vendor/lenovo/b8000/proprietary/lib/drm:system/lib/drm \
    vendor/lenovo/b8000/proprietary/lib/drm/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so \
    vendor/lenovo/b8000/proprietary/lib/libusc.so:system/lib/libusc.so \
    vendor/lenovo/b8000/proprietary/lib/libsrv_init.so:system/lib/libsrv_init.so \
    vendor/lenovo/b8000/proprietary/lib/libBLPP.so:system/lib/libBLPP.so \
    vendor/lenovo/b8000/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/lenovo/b8000/proprietary/lib/libglslcompiler.so:system/lib/libglslcompiler.so \
    vendor/lenovo/b8000/proprietary/lib/libpvrANDROID_WSEGL.so:system/lib/libpvrANDROID_WSEGL.so \
    vendor/lenovo/b8000/proprietary/lib/libpvr2d.so:system/lib/libpvr2d.so \
    vendor/lenovo/b8000/proprietary/lib/libWVStreamControlAPI_L3.so:system/lib/libWVStreamControlAPI_L3.so \
    vendor/lenovo/b8000/proprietary/lib/libsrv_um.so:system/lib/libsrv_um.so \
    vendor/lenovo/b8000/proprietary/lib/libPVRScopeServices.so:system/lib/libPVRScopeServices.so
